algoritmo "MaiorDeIdade"
// Função :  Verificar a idade
// Autor :   Gabriel Caspirro Demarchi
// Data : 18/05/2023
// Seção de Declarações 
var
nome: caractere
idade: inteiro
inicio
escreval("Digite seu nome: ")
leia(nome)
escreval("Digite sua idade: ")
leia(idade)

se(idade >= 18) entao
   escreval(nome, ", você é maior de idade!")
senao
   escreval(nome, ", você é menor de idade!")
fimse

fimalgoritmo
