algoritmo "Numero"
// Função : Dizer se um número está no intervalo entre 100 e 200
// Autor : Gabriel Caspirro Demarchi
// Data : 25/05/2023
// Seção de Declarações
var
num: real
inicio
escreval("Digite um número: ")
leia(num)

se ((num >= 100) e (num <= 200)) entao
   escreval("Esse número está entre 100 e 200")
senao
   escreval("Esse número não está entre 100 e 200")
fimse
fimalgoritmo
